//! Dev tooling: schema generation, local checks.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};
use videocaptionerr_contracts::error::ErrorCode;
use videocaptionerr_contracts::protocol::PROTOCOL_VERSION;
use videocaptionerr_contracts::version::{CONTRACTS_VERSION, SCHEMA_VERSION};

#[derive(Parser)]
#[command(name = "xtask", about = "VideoCaptionerR workspace tasks")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate JSON Schema fixtures and error-code lists under schemas/.
    GenSchemas {
        #[arg(long, default_value = "schemas")]
        out: PathBuf,
    },
    /// Run fmt + clippy -D warnings + tests.
    Check,
    /// Verify DDD crate dependency and source-boundary rules.
    VerifyArchitecture,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::GenSchemas { out } => gen_schemas(&out)?,
        Commands::Check => check()?,
        Commands::VerifyArchitecture => verify_architecture()?,
    }
    Ok(())
}

fn gen_schemas(out: &Path) -> Result<()> {
    fs::create_dir_all(out).with_context(|| format!("mkdir {}", out.display()))?;

    let meta = serde_json::json!({
        "schema_version": SCHEMA_VERSION,
        "contracts_version": CONTRACTS_VERSION,
        "protocol_version": PROTOCOL_VERSION,
    });
    write_json(&out.join("meta.json"), &meta)?;

    let codes: Vec<&str> = ErrorCode::all().iter().map(|c| c.as_str()).collect();
    write_json(&out.join("error_codes.json"), &serde_json::json!(codes))?;

    // Minimal hand-maintained JSON Schema documents derived from contracts.
    // Full schemars export can replace these later without changing the path.
    let transcript_schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://videocaptionerr.local/schemas/transcript.json",
        "title": "Transcript",
        "type": "object",
        "required": [
            "schema_version", "revision", "source_hash", "engine",
            "words", "cues", "next_cue_id", "timeline_source"
        ],
        "properties": {
            "schema_version": { "type": "integer", "minimum": 1 },
            "revision": { "type": "integer", "minimum": 1 },
            "source_hash": { "type": "string" },
            "language": { "type": ["string", "null"] },
            "engine": { "type": "object" },
            "words": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["text", "start_ms", "end_ms", "prob"],
                    "properties": {
                        "text": { "type": "string" },
                        "start_ms": { "type": "integer", "minimum": 0 },
                        "end_ms": { "type": "integer", "minimum": 0 },
                        "prob": { "type": "number" }
                    }
                }
            },
            "cues": { "type": "array" },
            "next_cue_id": { "type": "integer", "minimum": 1 },
            "timeline_source": {
                "type": "string",
                "enum": ["asr_words", "imported_cue"]
            }
        },
        "additionalProperties": true
    });
    write_json(&out.join("transcript.schema.json"), &transcript_schema)?;

    let protocol_schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://videocaptionerr.local/schemas/protocol_envelope.json",
        "title": "ProtocolEnvelope",
        "type": "object",
        "required": ["protocol_version", "session_id", "seq", "type"],
        "properties": {
            "protocol_version": { "type": "integer", "const": PROTOCOL_VERSION },
            "session_id": { "type": "string" },
            "request_id": { "type": ["integer", "null"] },
            "seq": { "type": "integer", "minimum": 0 },
            "type": { "type": "string" },
            "data": {}
        },
        "additionalProperties": true
    });
    write_json(&out.join("protocol_envelope.schema.json"), &protocol_schema)?;

    // Python fixture constants
    let py_dir = out.join("python");
    fs::create_dir_all(&py_dir)?;
    let py = format!(
        r#"# Generated by xtask gen-schemas — do not hand-edit.
PROTOCOL_VERSION = {PROTOCOL_VERSION}
SCHEMA_VERSION = {SCHEMA_VERSION}
ERROR_CODES = {codes:?}
"#
    );
    fs::write(py_dir.join("constants.py"), py)?;

    // TypeScript error codes
    let ts_dir = out.join("ts");
    fs::create_dir_all(&ts_dir)?;
    let mut ts = String::from("// Generated by xtask gen-schemas — do not hand-edit.\n");
    ts.push_str(&format!(
        "export const SCHEMA_VERSION = {SCHEMA_VERSION};\n"
    ));
    ts.push_str(&format!(
        "export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n"
    ));
    ts.push_str("export const ERROR_CODES = [\n");
    for c in &codes {
        ts.push_str(&format!("  \"{c}\",\n"));
    }
    ts.push_str("] as const;\n");
    fs::write(ts_dir.join("error_codes.ts"), ts)?;

    println!("wrote schemas under {}", out.display());
    Ok(())
}

fn write_json(path: &Path, value: &serde_json::Value) -> Result<()> {
    let text = serde_json::to_string_pretty(value)?;
    fs::write(path, text + "\n")?;
    Ok(())
}

fn check() -> Result<()> {
    run(Command::new("cargo").args(["fmt", "--all", "--", "--check"]))?;
    run(Command::new("cargo").args([
        "clippy",
        "--workspace",
        "--all-targets",
        "--all-features",
        "--",
        "-D",
        "warnings",
    ]))?;
    run(Command::new("cargo").args(["test", "--workspace"]))?;
    run(Command::new("cargo").args(["run", "-p", "xtask", "--", "verify-architecture"]))?;
    Ok(())
}

fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd.status().context("spawn command")?;
    if !status.success() {
        bail!("command failed: {status}");
    }
    Ok(())
}

fn verify_architecture() -> Result<()> {
    let output = Command::new("cargo")
        .args(["metadata", "--format-version", "1", "--no-deps"])
        .output()
        .context("run cargo metadata")?;
    if !output.status.success() {
        bail!("cargo metadata failed: {}", output.status);
    }
    let metadata: serde_json::Value =
        serde_json::from_slice(&output.stdout).context("parse cargo metadata output")?;
    let packages = metadata
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .context("cargo metadata packages missing")?;

    let dependencies = |package_name: &str| -> Result<Vec<String>> {
        let package = packages
            .iter()
            .find(|package| {
                package.get("name").and_then(serde_json::Value::as_str) == Some(package_name)
            })
            .with_context(|| format!("package {package_name} missing from metadata"))?;
        Ok(package
            .get("dependencies")
            .and_then(serde_json::Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(|dependency| {
                dependency
                    .get("name")
                    .and_then(serde_json::Value::as_str)
                    .map(str::to_owned)
            })
            .collect())
    };

    assert_no_dependencies(
        "videocaptionerr-core",
        &dependencies("videocaptionerr-core")?,
        &[
            "videocaptionerr-store",
            "videocaptionerr-asr",
            "videocaptionerr-llm",
            "videocaptionerr-platform",
            "videocaptionerr-bootstrap",
        ],
    )?;
    assert_no_dependencies(
        "videocaptionerr-cli",
        &dependencies("videocaptionerr-cli")?,
        &[
            "videocaptionerr-store",
            "videocaptionerr-asr",
            "videocaptionerr-llm",
            "videocaptionerr-platform",
        ],
    )?;
    assert_no_dependencies(
        "videocaptionerr-domain",
        &dependencies("videocaptionerr-domain")?,
        &[
            "videocaptionerr-contracts",
            "videocaptionerr-core",
            "videocaptionerr-store",
            "videocaptionerr-asr",
            "videocaptionerr-llm",
            "videocaptionerr-platform",
            "videocaptionerr-bootstrap",
        ],
    )?;
    verify_desktop_boundary()?;

    let mut source_files = Vec::new();
    collect_files(Path::new("crates"), &mut source_files)?;
    for path in source_files {
        let text = fs::read_to_string(&path)
            .with_context(|| format!("read source file {}", path.display()))?;
        let path_text = path.to_string_lossy();
        if !path_text.starts_with("crates/store/")
            && ["SELECT ", "INSERT ", "UPDATE ", "DELETE "]
                .iter()
                .any(|needle| text.contains(needle))
        {
            bail!("raw SQL found outside store: {}", path.display());
        }
        if !path_text.starts_with("crates/store/") && text.contains(".conn(") {
            bail!(
                "SQLite connection escape found outside store: {}",
                path.display()
            );
        }
        if path_text.starts_with("crates/cli/")
            && [
                "videocaptionerr_store",
                "videocaptionerr_asr",
                "videocaptionerr_llm",
                "videocaptionerr_platform",
            ]
            .iter()
            .any(|needle| text.contains(needle))
        {
            bail!("CLI imports a concrete adapter: {}", path.display());
        }
    }

    println!("architecture verification passed");
    Ok(())
}

fn assert_no_dependencies(
    package: &str,
    dependencies: &[String],
    forbidden: &[&str],
) -> Result<()> {
    for name in forbidden {
        if dependencies.iter().any(|dependency| dependency == name) {
            bail!("{package} must not depend on {name}");
        }
    }
    Ok(())
}

fn verify_desktop_boundary() -> Result<()> {
    let manifest_path = Path::new("apps/desktop/src-tauri/Cargo.toml");
    if !manifest_path.is_file() {
        bail!("desktop manifest missing: {}", manifest_path.display());
    }
    let manifest = fs::read_to_string(manifest_path)
        .with_context(|| format!("read desktop manifest {}", manifest_path.display()))?;
    for required in ["videocaptionerr-bootstrap", "videocaptionerr-contracts"] {
        if !manifest.contains(required) {
            bail!("desktop must depend on {required}");
        }
    }
    for forbidden in [
        "videocaptionerr-core",
        "videocaptionerr-domain",
        "videocaptionerr-asr",
        "videocaptionerr-llm",
        "videocaptionerr-platform",
        "videocaptionerr-store",
    ] {
        if manifest
            .lines()
            .any(|line| line.trim_start().starts_with(&format!("{forbidden} =")))
        {
            bail!("desktop must not depend directly on {forbidden}");
        }
    }

    let mut source_files = Vec::new();
    collect_files(Path::new("apps/desktop/src-tauri/src"), &mut source_files)?;
    for path in source_files {
        let text = fs::read_to_string(&path)
            .with_context(|| format!("read desktop source {}", path.display()))?;
        for forbidden in [
            "videocaptionerr_core",
            "videocaptionerr_domain",
            "videocaptionerr_asr",
            "videocaptionerr_llm",
            "videocaptionerr_platform",
            "videocaptionerr_store",
        ] {
            if text.contains(forbidden) {
                bail!(
                    "desktop source imports concrete adapter {forbidden}: {}",
                    path.display()
                );
            }
        }
    }
    Ok(())
}

fn collect_files(root: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    if !root.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(root).with_context(|| format!("read {}", root.display()))? {
        let path = entry?.path();
        if path.is_dir() {
            collect_files(&path, files)?;
        } else if path.extension().and_then(|value| value.to_str()) == Some("rs") {
            files.push(path);
        }
    }
    Ok(())
}
