//! Dev tooling: schema generation, local checks.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};
use clap::{Parser, Subcommand};
use videocaptionerr_contracts::error::ErrorCode;
use videocaptionerr_contracts::protocol::PROTOCOL_VERSION;
use videocaptionerr_contracts::version::{CONTRACTS_VERSION, SCHEMA_VERSION};

#[derive(Parser)]
#[command(name = "xtask", about = "VideoCaptionerR workspace tasks")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate JSON Schema fixtures and error-code lists under schemas/.
    GenSchemas {
        #[arg(long, default_value = "schemas")]
        out: PathBuf,
    },
    /// Run fmt + clippy -D warnings + tests.
    Check,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Commands::GenSchemas { out } => gen_schemas(&out)?,
        Commands::Check => check()?,
    }
    Ok(())
}

fn gen_schemas(out: &Path) -> Result<()> {
    fs::create_dir_all(out).with_context(|| format!("mkdir {}", out.display()))?;

    let meta = serde_json::json!({
        "schema_version": SCHEMA_VERSION,
        "contracts_version": CONTRACTS_VERSION,
        "protocol_version": PROTOCOL_VERSION,
    });
    write_json(&out.join("meta.json"), &meta)?;

    let codes: Vec<&str> = ErrorCode::all().iter().map(|c| c.as_str()).collect();
    write_json(&out.join("error_codes.json"), &serde_json::json!(codes))?;

    // Minimal hand-maintained JSON Schema documents derived from contracts.
    // Full schemars export can replace these later without changing the path.
    let transcript_schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://videocaptionerr.local/schemas/transcript.json",
        "title": "Transcript",
        "type": "object",
        "required": [
            "schema_version", "revision", "source_hash", "engine",
            "words", "cues", "next_cue_id", "timeline_source"
        ],
        "properties": {
            "schema_version": { "type": "integer", "minimum": 1 },
            "revision": { "type": "integer", "minimum": 1 },
            "source_hash": { "type": "string" },
            "language": { "type": ["string", "null"] },
            "engine": { "type": "object" },
            "words": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": ["text", "start_ms", "end_ms", "prob"],
                    "properties": {
                        "text": { "type": "string" },
                        "start_ms": { "type": "integer", "minimum": 0 },
                        "end_ms": { "type": "integer", "minimum": 0 },
                        "prob": { "type": "number" }
                    }
                }
            },
            "cues": { "type": "array" },
            "next_cue_id": { "type": "integer", "minimum": 1 },
            "timeline_source": {
                "type": "string",
                "enum": ["asr_words", "imported_cue"]
            }
        },
        "additionalProperties": true
    });
    write_json(&out.join("transcript.schema.json"), &transcript_schema)?;

    let protocol_schema = serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://videocaptionerr.local/schemas/protocol_envelope.json",
        "title": "ProtocolEnvelope",
        "type": "object",
        "required": ["protocol_version", "session_id", "seq", "type"],
        "properties": {
            "protocol_version": { "type": "integer", "const": PROTOCOL_VERSION },
            "session_id": { "type": "string" },
            "request_id": { "type": ["integer", "null"] },
            "seq": { "type": "integer", "minimum": 0 },
            "type": { "type": "string" },
            "data": {}
        },
        "additionalProperties": true
    });
    write_json(&out.join("protocol_envelope.schema.json"), &protocol_schema)?;

    // Python fixture constants
    let py_dir = out.join("python");
    fs::create_dir_all(&py_dir)?;
    let py = format!(
        r#"# Generated by xtask gen-schemas — do not hand-edit.
PROTOCOL_VERSION = {PROTOCOL_VERSION}
SCHEMA_VERSION = {SCHEMA_VERSION}
ERROR_CODES = {codes:?}
"#
    );
    fs::write(py_dir.join("constants.py"), py)?;

    // TypeScript error codes
    let ts_dir = out.join("ts");
    fs::create_dir_all(&ts_dir)?;
    let mut ts = String::from("// Generated by xtask gen-schemas — do not hand-edit.\n");
    ts.push_str(&format!(
        "export const SCHEMA_VERSION = {SCHEMA_VERSION};\n"
    ));
    ts.push_str(&format!(
        "export const PROTOCOL_VERSION = {PROTOCOL_VERSION};\n"
    ));
    ts.push_str("export const ERROR_CODES = [\n");
    for c in &codes {
        ts.push_str(&format!("  \"{c}\",\n"));
    }
    ts.push_str("] as const;\n");
    fs::write(ts_dir.join("error_codes.ts"), ts)?;

    println!("wrote schemas under {}", out.display());
    Ok(())
}

fn write_json(path: &Path, value: &serde_json::Value) -> Result<()> {
    let text = serde_json::to_string_pretty(value)?;
    fs::write(path, text + "\n")?;
    Ok(())
}

fn check() -> Result<()> {
    run(Command::new("cargo").args(["fmt", "--all", "--", "--check"]))?;
    run(Command::new("cargo").args([
        "clippy",
        "--workspace",
        "--all-targets",
        "--all-features",
        "--",
        "-D",
        "warnings",
    ]))?;
    run(Command::new("cargo").args(["test", "--workspace"]))?;
    Ok(())
}

fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd.status().context("spawn command")?;
    if !status.success() {
        bail!("command failed: {status}");
    }
    Ok(())
}
